### ISSUE TITLE
代码来源

### ISSUE THREAD

**Issue by abc-132** [Event-AHU/VcT_Remote_Sensing_Change_Detection#1]
请问一下这篇文章的代码什么时候可以开源呢 ？

**Comment by wangxiao5791509** [comment]
@abc-132  hi, this code is available now.

**Comment by abc-132** [comment]
非常感谢您对代码的开源 


| |
chentao0701cvb
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Xiao ***@***.***> |
| 发送日期 | 2023年10月29日 20:52 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Event-AHU/VcT_Remote_Sensing_Change_Detection] 代码来源 (Issue #1) |

Closed #1 as completed.
