### ISSUE TITLE
Dataset error

### ISSUE THREAD

**Issue by luy0222** [Event-AHU/VcT_Remote_Sensing_Change_Detection#2]
Hello, I used your DSIFN dataset for training and encountered an error during the training process. After investigation, I found that the 'A/1285_1.png' file was corrupted. I am wondering if this is a problem with the dataset itself or if it is due to my download. I have downloaded it twice but still encounter the same issue.

**Comment by wangxiao5791509** [comment]
@luy0222  Hi, this figure may be broken when compressing. We update this figure in the Github: https://github.com/Event-AHU/VcT_Remote_Sensing_Change_Detection/blob/main/figures/1285_1.zip 

you can try this. Thanks for your feedback.

**Comment by luy0222** [comment]
Thank you for your quick reply

**Comment by wangxiao5791509** [comment]
@luy0222   我们也提供了百度网盘下载方式。欢迎尝试。
