### ISSUE TITLE
The checkpoints zip can't be downloaded

### ISSUE THREAD

**Issue by mengdan-tan** [Event-AHU/VcT_Remote_Sensing_Change_Detection#3]
I can't download the checkpoints zip in the website https://www.dropbox.com/scl/fi/bc8thurpi51385m7q3c6u/VcT_checkpoints.zip?rlkey=pzjx52tfomno0y1fv4gmnxu0p&dl=0.

**Comment by mengdan-tan** [comment]
My e-mail is tanmengdan@outlook.com,thank you.

**Comment by wangxiao5791509** [comment]
> My e-mail is [tanmengdan@outlook.com](mailto:tanmengdan@outlook.com),thank you.

我们提供了百度网盘下载方式。请尝试这种方式。
