### ISSUE TITLE
demo代码

### ISSUE THREAD

**Issue by bobo59** [Event-AHU/VcT_Remote_Sensing_Change_Detection#4]
你好，请问能提供检测的demo代码吗。我使用BIT的代码后报错RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`。感觉应该是维度有问题。

**Comment by Vegetable2dog** [comment]
请问你解决了吗，我也出现了同样的问题

**Comment by ChengxinHU** [comment]
我觉得是decoder的问题，token的输入和x不是一个维度，不知道怎么做到的前向传播

**Comment by chengtianxiu** [comment]
> 你好，请问能提供检测的demo代码吗。我使用BIT的代码后报错RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`。感觉应该是维度有问题。

您可以直接尝试我们提供的 Evaluate 方式
