### ISSUE TITLE
indice0.txt 和 indice1.txt如何获取?

### ISSUE THREAD

**Issue by Fishero-xZhang** [Event-AHU/VcT_Remote_Sensing_Change_Detection#5]
你好，当我修改了batch_size或输入尺寸，默认的indice0.txt 和 indice1.txt给定的tensor维度会不匹配，应该如何自己根据不同维度生成这两个文件。

**Comment by Fishero-xZhang** [comment]
打印读取indice0.txt 和 indice1.txt的tensor及a的维度。
![code](https://github.com/Event-AHU/VcT_Remote_Sensing_Change_Detection/assets/54128898/52f1c83a-d624-4a1e-ab68-e2d5c5ed4ec9)
报错如下：
![error](https://github.com/Event-AHU/VcT_Remote_Sensing_Change_Detection/assets/54128898/e3a526f7-095c-4a0b-9304-014a370518d6)

**Comment by chengtianxiu** [comment]
> 你好，当我修改了batch_size或输入尺寸，默认的indice0.txt 和 indice1.txt给定的tensor维度会不匹配，应该如何自己根据不同维度生成这两个文件。

这里在构建K近邻图时使用的稀疏矩阵，先是生成n*n维度的mask，提前写入txt中的。可以根据不同的特征维度和K近邻图K值预先创建不同的mask记录非零值的坐标
[mask.zip](https://github.com/Event-AHU/VcT_Remote_Sensing_Change_Detection/files/13433083/mask.zip)

**Comment by Fishero-xZhang** [comment]
问题已解决，感谢您的回复。

**Comment by Vegetable2dog** [comment]
> 问题已解决，感谢您的回复。

可以请教下您是怎么解决的吗
