### ISSUE TITLE
特征图可视化

### ISSUE THREAD

**Issue by bobo59** [Event-AHU/VcT_Remote_Sensing_Change_Detection#6]
你好，请问你们的特征图可视化是如何实现的。

![image](https://github.com/Event-AHU/VcT_Remote_Sensing_Change_Detection/assets/77272280/80477f68-b5a7-4b7f-a2ae-ce7d1b9a8abd)

**Comment by chengtianxiu** [comment]
用opencv库就可以实现热力图，applyColorMap 方法

**Comment by chengtianxiu** [comment]
> Edit
> Report conte

用opencv库就可以实现热力图，applyColorMap 方法

**Comment by chengtianxiu** [comment]
> 你好，请问你们的特征图可视化是如何实现的。
> 
> ![image](https://private-user-images.githubusercontent.com/77272280/289778788-80477f68-b5a7-4b7f-a2ae-ce7d1b9a8abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjA3NDgsIm5iZiI6MTcwNTA2MDQ0OCwicGF0aCI6Ii83NzI3MjI4MC8yODk3Nzg3ODgtODA0NzdmNjgtYjVhNy00YjdmLWEyYWUtY2U3ZDFiOWE4YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDExNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MmFiZTFiMzhmY2JhMDZjY2QzMDdjODk5NGU5YmFlZTgwZmM2N2QzMjI2NzlkMDM5YTdiMzkxNjRiZTdiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.09I5lDn7Dr2VGvh_iapQaZ5f1__JRQ0YmIAtq9z5GfA)

用opencv库就可以实现热力图，applyColorMap 方法
